or3nQ6H_1_WfwkMZI_qYFrcdmhHkjko-s.p.be19f591.woff2:1
           Failed to load resource: the server responded with a status of 403 ()
gyByhwUxId8gMEwcGFWNOITd-s.p.da1ebef7.woff2:1

           Failed to load resource: the server responded with a status of 403 ()
react-dom-client.development.js:24914 Download the React DevTools for a better development experience: https://react.dev/link/react-devtools
page.tsx:68  Server   Error: Route "/creators/[creatorId]" used `params.creatorId`. `params` should be awaited before using its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
    at CreatorProfilePage (page.tsx:68:43)
    at resolveErrorDev (react-server-dom-turbopack-client.browser.development.js:1838:46)
    at getOutlinedModel (react-server-dom-turbopack-client.browser.development.js:1322:22)
    at parseModelString (react-server-dom-turbopack-client.browser.development.js:1462:15)
    at Array.<anonymous> (react-server-dom-turbopack-client.browser.development.js:2267:18)
    at JSON.parse (<anonymous>)
    at resolveConsoleEntry (react-server-dom-turbopack-client.browser.development.js:2102:28)
    at processFullStringRow (react-server-dom-turbopack-client.browser.development.js:2243:11)
    at processFullBinaryRow (react-server-dom-turbopack-client.browser.development.js:2206:7)
    at progress (react-server-dom-turbopack-client.browser.development.js:2452:17)
CreatorProfilePage @ page.tsx:68
gyByhwUxId8gMEwcGFWNOITd-s.p.da1ebef7.woff2:1

           Failed to load resource: the server responded with a status of 403 ()
or3nQ6H_1_WfwkMZI_qYFrcdmhHkjko-s.p.be19f591.woff2:1

           Failed to load resource: the server responded with a status of 403 ()
warn-once.ts:6 Image with src "https://picsum.photos/seed/ddWzdR7qBtWbmnMNKiQZFkGHWkD3_cover/1200/400?grayscale&blur=2" has "fill" but is missing "sizes" prop. Please add it to improve page performance. Read more: https://nextjs.org/docs/api-reference/next/image#sizes
warnOnce @ warn-once.ts:6
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
use-websocket.ts:16 WebSocket connection to 'wss://6000-firebase-studio-1746916122117.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev/_next/webpack-hmr' failed:
(anonymous) @ use-websocket.ts:16
ddWzdR7qBtWbmnMNKiQZFkGHWkD3:1 Access to fetch at 'https://us-central1-tipkesho-b8e63.cloudfunctions.net/sendTipViaMpesa' from origin 'https://6000-firebase-studio-1746916122117.cluster-ombtxv25tbd6yrjpp3lukp6zhc.cloudworkstations.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
tipping-modal.tsx:127

           POST https://us-central1-tipkesho-b8e63.cloudfunctions.net/sendTipViaMpesa net::ERR_FAILED
postJSON @ service.ts:222
callAtURL @ service.ts:299
await in callAtURL
call @ service.ts:261
(anonymous) @ service.ts:186
handleSubmitTip @ tipping-modal.tsx:127
executeDispatch @ react-dom-client.development.js:16426
runWithFiberInDEV @ react-dom-client.development.js:1510
processDispatchQueue @ react-dom-client.development.js:16476
(anonymous) @ react-dom-client.development.js:17074
batchedUpdates$1 @ react-dom-client.development.js:3253
dispatchEventForPluginEventSystem @ react-dom-client.development.js:16630
dispatchEvent @ react-dom-client.development.js:20716
dispatchDiscreteEvent @ react-dom-client.development.js:20684
tipping-modal.tsx:143 Error calling sendTipViaMpesa function: FirebaseError: internal
error @ intercept-console-error.ts:41
handleSubmitTip @ tipping-modal.tsx:143
await in handleSubmitTip
executeDispatch @ react-dom-client.development.js:16426
runWithFiberInDEV @ react-dom-client.development.js:1510
processDispatchQueue @ react-dom-client.development.js:16476
(anonymous) @ react-dom-client.development.js:17074
batchedUpdates$1 @ react-dom-client.development.js:3253
dispatchEventForPluginEventSystem @ react-dom-client.development.js:16630
dispatchEvent @ react-dom-client.development.js:20716
dispatchDiscreteEvent @ react-dom-client.development.js:20684